config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  #get 'pages/index'

  get 'pages/about_us'

  get 'pages/faq'

  get 'pages/tos'

  get 'pages/contact_us'
  
  get 'pages/profile'
  
  get 'auth/:provider/callback', to: "sessions#create"
  
  delete 'sign_out', to: "sessions#destroy", as: 'sign_out' 
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    def self.sign_in_from_omniauth(auth)
       find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
    end
    
    def self.create_user_from_omniauth(auth)
        create(
           provider: auth['provider'],
           uid: auth['uid'],
           name: auth['info']['name']
        )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private
  
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_auth
  def index
  end

  def about_us
  end

  def faq
  end

  def tos
  end

  def contact_us
  end
  
  def profile
  end
  
  private
  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
      auth = request.env["omniauth.auth"]
      session[:omniauth] = auth.except('extra')
      user = User.sign_in_from_omniauth(auth)
      session[:user_id] = user.id
      redirect_to root_url, notice: "SIGNED IN"
    end
    
    def destroy
        session[:user_id] = nil
        session[:omniauth] = nil
        redirect_to root_url, notice: "SIGNED OUT"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_menu.html.erb
<li><%= link_to "Compañia", pages_about_us_path  %></li>

<li><%= link_to "Carta Bar", pages_faq_path  %></li>

<li><%= link_to "Terminos de servicio", pages_tos_path  %></li>

<li><%= link_to "Locales", pages_contact_us_path  %></li>

<li><%= link_to "Registrese", pages_contact_us_path  %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Proyectokaraoke" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid" STYLE="background-color:#100001">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1><%= link_to root_path do %>Proyectokaraoke<% end %></h1>
        </div>
      </div>
  </nav> 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" >
      <% if current_user %>
        <li>Logueado como: <%= current_user.name %>  <%= image_tag(@auth['info']['image'], width:'60', height:'60', class:'img-circle') %><% end %></li>
        <br>
        <br>
        <li><% link_to "Sign_out", 'sign_out', method: :delete%></li>
      <% else %> 
        <br>
        <li><%= link_to "auth/facebook" do %><%= image_tag('facebook.png', width: '50', height: '50', class:'img-circle') %><% end %></li>
        <li><%= link_to "auth/twitter" do %><%= image_tag('twitter.png', width: '50', height: '50', class:'img-circle') %><% end %></li>
        <li><%= link_to "auth/github" do %><%= image_tag('github.png', width: '50', height: '50', class:'img-circle') %><% end %></li>
      </ul>
    </div>
  
  <% flash.each do |key, value| %>
  <div class="alert alert-info"><% value %></div>
  <% end %>
  
  <% if current_user %>
    <div class="text-center">
      <h1>Bienvenido, <%= current_user.name%> </h1>
      <h4>Logueado con -> <strong><em><% @auth['provider'].capitalize %></em></strong></h4>
    <%= image_tag('logo.png',width: '200', height: '200', class:'img-circle')%>
    </div>
  <% end %>
  <br>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
                <%= render 'layouts/menu' %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row--> 
      <br>
      <br>
      <br>
        <footer>
          <p>&copy; Smart Solutions Company 2016</p>
        </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/internal.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Proyectokaraoke" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Proyectokaraoke</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'layouts/menu' %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
            <div class="page-header">
              <h1><%= yield :header_title %> <small><%= yield :header_sub_title %></small>
            </h1>
           </div>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
                <%= render 'layouts/menu' %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Smart Solutions Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Acerca de nosotros</h1>
<p>En ProyectoKaraoke nos gusta cantar y nos gusta que cante todo el mundo. Y por eso hemos creado el primer karaoke digital que te permite 
cantar allá donde estés, con el catálogo más amplio del mercado, y con las mejores y más avanzadas herramientas para hacer 
tu experiencia fácil y divertida. Y como cantar es un acto social, si lo deseas podrás grabarte cantando solo o con amigos 
y compartir ese momento en la Red.</p>


<h3>Un conjunto armónico</h3>
<br>
<div align=center>
   <%= image_tag "armonico.jpg"%>
</div>
<br>
<p>Para cumplir nuestra misión hemos combinado una serie de ingredientes clave: innovación y tecnología, contenidos, 
un gran equipo de trabajo con mucha experiencia en el sector, inversores de referencia que han confiado en el proyecto 
y socios de primer nivel para llegar juntos a donde nosotros solos no podemos.</p>

app/views/pages/contact_us.html.erb
<h1>Locales</h1>

<div class="imagen" align=center>
  
  <%= image_tag  "local1.jpg"%>
  <%= image_tag  "local2.jpg"%>
  <%= image_tag  "local3.jpg"%>
  <%= image_tag  "local4.jpg"%>
</div>

app/views/pages/faq.html.erb
<h1>CARTA BAR</h1>

<div align=center>
  
  <%= image_tag  "cartabar.jpg"%>
</div>

app/views/pages/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->

  <ol class="carousel-indicators">

    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>

    <li data-target="#carousel-example-generic" data-slide-to="1"></li>

    <li data-target="#carousel-example-generic" data-slide-to="2"></li>

  </ol>

  <!-- Wrapper for slides -->

  <div class="carousel-inner" role="listbox">

    <div class="item active">

      <%= image_tag "img_1.jpg", html: { alt: "rest_slider1" } %>

      <div class="carousel-caption">

        <h3>Los mejores locales</h3>

        <p>The best for you</p>

      </div>

    </div>

    <div class="item">

      <%= image_tag "img_2.jpg", html: { alt: "rest_slider2" } %>

      <div class="carousel-caption">

        <h3>Los mejores equipos de sonido</h3>

        <p>Best quality</p>

      </div>

    </div>

    <div class="item">

      <%= image_tag "img_3.jpg", html: { alt: "rest_slider3" }%>

      <div class="carousel-caption">

        <h3>El mejor servicio</h3>

        <p>Best quality</p>

      </div>

    </div>

  </div>

  <!-- Controls -->

  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">

    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

    <span class="sr-only">Previous</span>

  </a>

  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">

    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

    <span class="sr-only">Next</span>

  </a>

</div>


<div class="jumbotron">

  <h1 class="ok">Bienvenido</h1>

  <p>Saca el artista que llevas dentro!</p>

  <p><a class="btn btn-primary btn-lg" href=<%= pages_about_us_path %> role="button">Adelante!</a></p>

</div>

app/views/pages/login.html.erb
<h1>LOGIN</h1>

app/views/pages/profile.html.erb
<h1>LOGIN</h1>

app/views/pages/tos.html.erb
<div align=center>
   <%= image_tag "terms.png"%>
</div>

<h2>Obligación de hacer un uso correcto del Portal y del Servicio.</h2>

<p>El Usuario tiene la obligación de hacer un uso correcto del Portal y de los Servicios, y para ello se compromete a utilizar 
el Portal y los Servicios de conformidad con la ley, las presentes Condiciones y demás avisos legales, reglamentos de uso e 
instrucciones puestos en su conocimiento, así como con la moral y las buenas costumbres generalmente aceptadas y el orden público.

En particular, y a título meramente indicativo y no exhaustivo, el Usuario se compromete a no transmitir, 
difundir o poner a disposición de terceros informaciones, datos, contenidos, mensajes, gráficos, dibujos, 
archivos de sonido y/o imagen, fotografías, grabaciones, software y, en general, cualquier clase de material que:
<br>
<br>
(a) De cualquier forma sea contrario, menosprecie o atente contra los derechos fundamentales y las libertades públicas reconocidas
constitucionalmente, en los Tratados internacionales y en el resto de la legislación;<
<br>
<br>
(b) Induzca, incite o promueva actuaciones delictivas, denigratorias, difamatorias, infamantes, violentas o, en general, 
contrarias a la ley, a la moral y buenas costumbres generalmente aceptadas o al orden público;
<br>
<br>
(c) Induzca, incite o promueva actuaciones, actitudes o pensamientos discriminatorios por razón de sexo, raza, 
religión, creencias,edad o condición;
<br>
<br>
(d) Incorpore, ponga a disposición o permita acceder a productos, elementos, mensajes y/o servicios delictivos,
violentos, ofensivos, nocivos, degradantes o, en general, contrarios a la ley, a la moral y a las buenas costumbres 
generalmente aceptadas o al orden público;
<br>
<br>
(e) Induzca o pueda inducir a un estado inaceptable de ansiedad o temor;
<br>
<br>
(f) Induzca o incite a involucrarse en prácticas peligrosas, de riesgo o nocivas para la salud y el equilibrio psíquico;
<br>
<br>
(g) Sea falso, ambiguo, inexacto, exagerado o extemporáneo, de forma que induzca o pueda inducir a error sobre su objeto 
o sobre las intenciones o propósitos del comunicante;
<br>
<br>
(h) Se encuentre protegido por cualesquiera derechos de propiedad intelectual o industrial pertenecientes a terceros,
sin que el Usuario haya obtenido previamente de sus titulares la autorización necesaria para llevar a cabo el uso que efectúa o pretende efectuar;</li>
<br>
<br>
(i) Viole los secretos empresariales de terceros;
<br>
<br>
(j) Sea contrario al derecho al honor, a la intimidad o a la propia imagen de las personas;
<br>
<br>
(k) De cualquier manera menoscabe el crédito de PRESTADOR DE SERVICIOS o de terceros.
</p>